version: '2'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  registration:
    image: mailcow-registration
    build: .
    environment:
      - REGISTER_QUOTA=128
      - REGISTER_DEFAULT_TOKEN_LENGTH=128
    ports:
      - 5000:5000
